---
pagetitle: "Marie Curie"
output:
  bookdown::html_document2:
    css: ["files/style.css", 
          "https://use.fontawesome.com/releases/v5.7.2/css/all.css",
          "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]
    includes:
      in_header: "files/header.html"
    number_sections: false
    selfcontained: true
    toc_float: true
    toc: true
    
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
options(knitr.kable.NA = '')
library(tidyverse)
library(knitr)
library(kableExtra)
library(RefManageR)
library(googlesheets4)

```


```{r tables, include=FALSE}
# bibliography items 
publications <- "files/curie.bib"

# CV items can be read from an excel sheet
#cv_entries <- readxl::read_xlsx("files/cv_entries.xlsx")
#cv_entries <- subset(cv_entries, show == T)

# or CV items can be read from a google sheet using the sheet id
# use sheets_deauth() when the sheet can be viewed by anyone with the link
googlesheets4::gs4_deauth()
cv_entries <- googlesheets4::read_sheet("1bzHcV8x1I4Z7tOA52dkKLEh27gUR39R3NelefmdrKgw", col_types = "c")
cv_entries <- subset(cv_entries, show == T)

# formatting positions with descriptions
longEntry <- function(data, showDesc = F){
  data %>%
  mutate(what = str_c("<span class='work-title'>", 
                      what, "</span><br> <i>", where, "</i>")) %>%
  mutate(what = ifelse(!is.na(description) & showDesc == T, 
                       str_c(what, "<br class='work-break'>", description), what)) %>%
  mutate(when = gsub(when, pattern = " --- ", replacement = " --- <br>")) %>%
  select(when, what) %>%
  kable(escape = F) %>%
  column_spec(1, width_min = "9em") 
}

# formatting for one-liner entries
shortEntry <- function(data, wide = T){
  data %>%
    select(when, what, where) %>% 
    kable(format = "html", align = "llr", escape = F) %>%
    column_spec(3, italic = T) %>%
    column_spec(2, width = "20em") %>%
    column_spec(1, width = ifelse(wide, "12em", "6em") )
}

bestOf <- function(l){
  # return the first non-na argument
  #print(head(data.frame(l)))
  r <- apply(data.frame(l), FUN = function(x){x[which(!is.na(x))][[1]]}, MAR = 1)
  return(r)
}

# general formatting
# all entries should have at least a year_begin and a what
cv_entries <- arrange(cv_entries, desc(pmax(year_end, year_begin, na.rm = T)), desc(year_begin), desc(month_begin)) 
stopifnot(all(!is.na(cv_entries$year_begin)))
cv_entries <- cv_entries %>%  
  mutate(month_begin = month.abb[as.numeric(month_begin)]) %>%
  mutate(month_end = month.abb[as.numeric(month_end)]) %>%
  mutate(when = bestOf(list(str_c(month_begin, " ", year_begin, " --- ", month_end, " ", year_end),
                            str_c(month_begin, " ", year_begin, " --- ", year_end),
                            str_c(year_begin, " --- ", year_end),
                            str_c(month_begin, " ", year_begin),
                            year_begin)))
```

<div class="printHider">
<span class="printTitle">Marie Curie</span>  
<i class="fas fa-envelope"></i>: &nbsp; mariecurie<i class="fas fa-at fa-sm"></i>ens.fr
<i class="fab fa-github"></i>: &nbsp; [mariecurie](https://github.com/<github-user>) 
<i class="fab fa-linkedin-in"></i>: &nbsp; [linkedin.com/marie-curie](https://www.linkedin.com/)
</div>


<div>
## Contact {.invisible}  
</div>

<div class = "row">
<div class = "col-md-6">


Some stuff about me:

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.
 
 
</div>


<div class = "col-md-6">
```{block type='col-6 grid-item', echo=TRUE}
<div class="info-box">

| Center | Left |
|:------:|:-----|
| <i class="fas fa-map-marker-alt"></i>|School of Physics & Chemistry,\
École Normale Supérieure|
| <i class="fas fa-envelope"></i> | mariecurie<i class="fas fa-at fa-sm"></i>ens.fr |
| <i class="ai ai-orcid ai-1x"></i> | [ORCID](https://orcid.org/<orcid-id>) |
| <i class="fab fa-github"></i> | [mariecurie](https://github.com/<github-user>) |


</div>
```
</div>
</div>


## Education {.nohead}

```{r education}
cv_entries %>% 
  filter(type == 'education') %>% 
  shortEntry()
```


## Publications {.nohead}

```{r publications}
snatchPrint <- function(bib){
  # extract data from bibentry
  refsList <- capture.output(PrintBibliography(bib))
    
  # add delim, and split entries
  refsList[which(nchar(refsList) == 0)] <- "<DELIM>"
  
  paste0(refsList, collapse = " ") %>% 
    strsplit(split = "<DELIM>") %>%
    unlist() -> entries
  
  # bold a name
  entries <- gsub("M Sklodowska-Curie", "__M Sklodowska-Curie__", fixed = T, entries)
  entries <- gsub("M Curie", "__M Curie__", fixed = T, entries)
  
  # remove numeric if necessary
  entries <- gsub('\\[[[:digit:]]\\] ', '', entries)
  
  return(entries)

}

makePubTable <- function(bib){
  # Function to include links to papers and code, as provided in the bibliography file
  # code link should be in the annote field of bib entries, or "NULL" if no code link.
  
  # reverse these to match date order of refs
  urls <- rev(bib$url)
  urls[is.null(urls)] <- NA
  annotes <- rev(bib$annote)
  annotes[is.null(annotes)] <- NA
  
 
  tibble(entry = snatchPrint(bib),
         paperLink = unlist(urls, use.names = FALSE), 
         codeLink = unlist(annotes, use.names = FALSE)) %>%
    mutate(paperLink = str_c("[paper]", "(", paperLink, ")")) %>%
    mutate(paperLink = cell_spec(paperLink, background = "var(--hl-col)",
                            font_size = "1.2em")) %>%
    mutate(codeLink = ifelse( (codeLink == 'NULL' | is.null(codeLink)), '', codeLink)) %>%
    mutate(codeLink = case_when(codeLink != '' ~ str_c("[code]", "(", codeLink, ")"))) %>%
    mutate(codeLink = case_when(codeLink != '' ~ cell_spec(codeLink, background = "var(--hl-col)",
                                                           font_size = "1.2em")))
    
}

oops <- BibOptions(bib.style = "numeric", match.author = "exact", 
                   sorting = 'ydnt', max.names = 99, first.inits = FALSE, 
                   style = "text", no.print.fields = c("doi","url","urldate", "issn"))


refs <- ReadBib(publications) 
NoCite(refs)


makePubTable(refs) %>%
    
    # Uncomment this to remove buttons to link to papers and code
    # (useful for printing to PDF)
    #select(entry) %>% 
    kable(escape = F) 


```


## Grants & Awards {.nohead}
```{r awards}
cv_entries %>% 
  filter(type == 'awards') %>% 
  longEntry(showDesc = T)
```


## Memberships & Affiliations {.nohead}
```{r affiliations}
cv_entries %>% 
  filter(type == "affiliations") %>% 
  shortEntry() 
```


## Teaching {.nohead}
```{r teaching}
cv_entries %>% 
  filter(type == 'teaching') %>% 
  longEntry() 
```


## Work experience {.nohead}
```{r work}
cv_entries %>% 
  filter(type == 'work') %>% 
  longEntry()
```



